pxemngr: Don't use basename in Usage
When printing the usage, we report basename like :

    cm@edeploy:~$ pxemngr addsystem
    Usage: /srv/pxemngr/pxe/addsystem <system name> <MAC> [<MAC2>...]

The issue here it that we report a basename that cannot be use directly like :
    cm@edeploy:~$ /srv/pxemngr/pxe/addsystem
    Traceback (most recent call last):
      File "/srv/pxemngr/pxe/addsystem", line 13, in <module>
	from pxe.models import *
    ImportError: No module named pxe.models

It seems better to print the program name instead of basename to get a copy/pastable output message.